/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include <string.h>
#include <stdlib.h>
#include "DIALOG.h"
#include "EmWinHZFont.h"
#include "FramewinDLG.h"
#include "backupIF.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)

#define ID_TEXT_0     (GUI_ID_USER + 0x01)



#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_TEXT_3     (GUI_ID_USER + 0x04)
#define ID_TEXT_4     (GUI_ID_USER + 0x05)
#define ID_TEXT_5     (GUI_ID_USER + 0x06)
#define ID_TEXT_6     (GUI_ID_USER + 0x07)
#define ID_TEXT_7     (GUI_ID_USER + 0x08)
//#define ID_TEXT_8     (GUI_ID_USER + 0x09)

#define ID_TEXT_0_1     (GUI_ID_USER + 0x0A)
#define ID_TEXT_1_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2_1     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3_1     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4_1     (GUI_ID_USER + 0x0E)
#define ID_TEXT_5_1     (GUI_ID_USER + 0x0F)
#define ID_TEXT_6_1     (GUI_ID_USER + 0x10)
#define ID_TEXT_7_1     (GUI_ID_USER + 0x11)
//#define ID_TEXT_8_1     (GUI_ID_USER + 0x12)

#define  ID_EDIT_0     (GUI_ID_USER + 0x13)
#define  ID_EDIT_1     (GUI_ID_USER + 0x14)
#define  ID_EDIT_2     (GUI_ID_USER + 0x15)
#define  ID_EDIT_3     (GUI_ID_USER + 0x16)
#define  ID_EDIT_4     (GUI_ID_USER + 0x17)
#define  ID_EDIT_5     (GUI_ID_USER + 0x18)
#define  ID_EDIT_6     (GUI_ID_USER + 0x19)
#define  ID_EDIT_7     (GUI_ID_USER + 0x1A)
#define  ID_EDIT_8     (GUI_ID_USER + 0x1B)

#define ID_BUTTON_0     (GUI_ID_USER + 0x1C)
#define ID_BUTTON_1     (GUI_ID_USER + 0x1D)
#define ID_BUTTON_2     (GUI_ID_USER + 0x1E)

//#define ID_RADIO_0    (GUI_ID_USER + 0x1E)

#define ID_LISTBOX_0    (GUI_ID_USER + 0x1F)

#define ID_TEXT_8    (GUI_ID_USER + 0x20)
#define ID_TEXT_9    (GUI_ID_USER + 0x21)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  //{ RADIO_CreateIndirect, "Radio", ID_RADIO_0, 396, 20, 300, 200, 0, 0x3204, 0 },
  //{ LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 396, 60, 300, 200, 0, 0x0, 0 },
  	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 65, 20, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 65, 60, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 65, 100, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 65, 140, 88, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4, 65, 180, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5, 65, 220, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_6, 65, 260, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_7, 65, 300, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_9, 65, 340, 85, 25, 0, 0x0, 0 },

	{ TEXT_CreateIndirect, "Text", ID_TEXT_0_1, 250, 20, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1_1, 250, 60, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2_1, 250, 100, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3_1, 250, 140, 88, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4_1, 250, 180, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5_1, 250, 220, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_6_1, 250, 260, 85, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_7_1, 250, 300, 85, 25, 0, 0x0, 0 },



	{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 168, 20, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_1, 168, 60, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_2, 168, 100, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_3, 168, 140, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_4, 168, 180, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_5, 168, 220, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_6, 168, 260, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_7, 168, 300, 85, 25, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_8, 168, 340, 120, 25, 0, 0x0, 0 },

	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 65, 390, 80, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 396, 390, 80, 30, 0, 0x0, 0 },
	
	{ TEXT_CreateIndirect, "Text", ID_TEXT_8, 150, 390, 220, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

/*static LISTBOX_Handle hListBox;
static void createListBox(){
	
	//hListBox = LISTBOX_CreateEx(396, 60, 300, 200, WM_UNATTACHED, WM_CF_SHOW, 0, 0, NULL);
	hListBox=LISTBOX_Create(NULL, 396, 80, 300, 200, WM_CF_SHOW);
	LISTBOX_AddString(hListBox, "渐进式安全钳");
	LISTBOX_AddString(hListBox, "滚柱瞬时式");
	LISTBOX_AddString(hListBox, "其他瞬时式");
	LISTBOX_SetFont(hListBox,  &GUI_FontHZ16);
	//LISTBOX_SetDefaultBkColor();
	LISTBOX_SetBkColor(hListBox,LISTBOX_CI_SEL,GUI_GRAY);
	LISTBOX_SetTextColor(hListBox,LISTBOX_CI_SEL,GUI_WHITE);
} */
static WM_HMEM timer;

static void _cbDialog(WM_MESSAGE * pMsg) {
  	WM_HWIN hItem,hItext;
	int     NCode;
	int     Id,i;
	static char editID=ID_EDIT_0;
	// USER START (Optionally insert additional variables)
	// USER END
	int posiX, posiY, sizeX[2], sizeY[2];
	char editBuffer[30];
	switch (pMsg->MsgId) {
		case WM_INIT_DIALOG:
		BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), 0);
		BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), 0);
		BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2), 0);
		//Focussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), 0);
		//hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		
		//
		// Initialization of 'Framewin'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 36);
		FRAMEWIN_SetFont(hItem, &GUI_FontHZ16);
		FRAMEWIN_SetText(hItem, COMPANYNAME);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		timer = WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), 1, 30, 0); //~10ms
		//hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
		/*RADIO_SetFont(hItem, &GUI_FontHZ16);
		RADIO_SetText(hItem, "渐进式安全钳", 0);
		RADIO_SetText(hItem, "滚柱瞬时式", 1);
		RADIO_SetText(hItem, "其他瞬时式", 2);*/
		//LISTBOX_AddString(hItem, "渐进式安全钳");
    	//LISTBOX_AddString(hItem, "滚柱瞬时式");
    	//LISTBOX_AddString(hItem, "其他瞬时式");
    	//LISTBOX_SetFont(hItem,  &GUI_FontHZ16);
		//LISTBOX_SetDefaultBkColor();
		//LISTBOX_SetBkColor(hItem,LISTBOX_CI_SEL,GUI_GRAY);
		//LISTBOX_SetTextColor(hItem,LISTBOX_CI_SEL,GUI_WHITE);
		//RADIO_SetText(hItem, "除了不可脱落滚柱式安全钳", 3);
		//WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
		//WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "额定速度");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "节径");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "初速度");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "速度V1");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "速度V2");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "加速度A1");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "加速度A2");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "加速度A3");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "mm");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m2/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m2/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "m2/s");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetText(hItem, "安全钳类型");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

		//
		// Initialization of 'Text'
		//


		//
		// Initialization of 'Button'
		//

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_FontHZ16);		
		BUTTON_SetText(hItem, "下一步");	
		//
		// Initialization of 'Button'
		//

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_FontHZ16);		
		BUTTON_SetText(hItem, "返回");	
		//
		// Initialization of 'Button'
		//

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		EDIT_SetFont(hItem,&GUI_FontHZ16);		
		EDIT_SetText(hItem, "渐进式安全钳");	

		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[0] , 2017, 2017, 3000, 0, 0);
		EDIT_SetText(hItem, "2.00");

		//
		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[1] , 1, 1, 12, 0,0);
		EDIT_SetText(hItem, "240.0");
		//
		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[2] , 1, 1, 31,0,0);
		EDIT_SetText(hItem, "0.40");
		//
		// Initialization of 'Edit'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[3] , 0, 0, 23, 0,0);
		EDIT_SetText(hItem, "1.70");
		//
		// Initialization of 'Edit'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		//EDIT_SetMaxLen(editbox[4],4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[4] , 0, 0, 59, 0, 0);
		EDIT_SetText(hItem, "2.10");

		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[0] , 2017, 2017, 3000, 0, 0);
		EDIT_SetText(hItem, "0.50");

		//
		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[1] , 1, 1, 12, 0,0);
		EDIT_SetText(hItem, "0.10");
		//
		// Initialization of 'Edit'
		//
		hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		//EDIT_SetMaxLen(hItem,4);
		EDIT_SetFont(hItem,&GUI_FontHZ16);	
		//EDIT_SetDecMode(editbox[2] , 1, 1, 31,0,0);
		EDIT_SetText(hItem, "0.02");
		//
		// Initialization of 'Edit'
		//
		

		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	
		case WM_TIMER://~定时器
		/*if(0==getWindowSKBtimerBoot()){
			hItext = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			EDIT_SetText(hItext, "");
		}else{*/
			//EDIT_GetText(WM_GetFocussedWindow(), &editBuffer[0], sizeof(editBuffer));
			hItext = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
			switch(_config_content.sort){
			case 0:
				EDIT_SetText(hItext, "渐进式安全钳");
				break;
			case 1:
				EDIT_SetText(hItext, "滚柱瞬时式安全钳");
				break;
			case 2:
				EDIT_SetText(hItext, "其他形式瞬时式安全钳");
				break;	
			}
			
		//}
		WM_RestartTimer(timer, 100);
		break;
		case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
			case ID_EDIT_0:
			case ID_EDIT_1:
			case ID_EDIT_2:
			case ID_EDIT_3:
			case ID_EDIT_4:
			case ID_EDIT_5:
			case ID_EDIT_6:
			case ID_EDIT_7:
				switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
					//LISTBOX_SetDefaultBkColor(LISTBOX_CI_SEL,GUI_GRAY);
				// USER START (Optionally insert code for reacting on notification message)
					if(!button_Press.windowSKB){
						button_Press.windowSKB=1;
						for(i=ID_EDIT_0; i<=ID_EDIT_8; i++) EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 0);	//disable focus
						EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, Id), 1);
						WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin),Id));
						hItem = WM_GetDialogItem(pMsg->hWin, Id);
						EDIT_SetText(hItem, "");
						sizeX[0] = WM_GetWindowSizeX(WM_GetClientWindow(ui_page.configUi));
						sizeY[0] = WM_GetWindowSizeY(WM_GetClientWindow(ui_page.configUi));
						sizeX[1] = WM_GetWindowSizeX(ui_page.windowSKB);
						sizeY[1] = WM_GetWindowSizeY(ui_page.windowSKB);
						/*if(sizeX[0] - WM_GetWindowOrgX(pMsg->hWinSrc) < sizeX[1]) posiX = sizeX[0] - sizeX[1];
						else posiX = WM_GetWindowOrgX(pMsg->hWinSrc);
						if(sizeY[0]-WM_GetWindowOrgY(pMsg->hWinSrc)-WM_GetWindowSizeY(pMsg->hWinSrc) < sizeY[1])
						posiY = WM_GetWindowOrgY(pMsg->hWinSrc) - sizeY[1];
						else posiY = WM_GetWindowOrgY(pMsg->hWinSrc) + WM_GetWindowSizeY(pMsg->hWinSrc);*/
						posiX=(800-sizeX[1])/2;
						posiY=37;
						WM_MoveTo(ui_page.windowSKB, posiX, posiY);
						WM_ShowWindow(ui_page.windowSKB);
					}
					//setWindowSKBtimerBoot(0);
					// USER END
					// USER END
					break;
					case WM_NOTIFICATION_RELEASED:
					// USER START (Optionally insert code for reacting on notification message)

					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					// USER START (Optionally insert additional code for further notification handling)
					// USER END   
					}
				break;
		// USER START (Optionally insert additional message handling)
		// USER END
		case ID_EDIT_8:
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
					//LISTBOX_SetDefaultBkColor(LISTBOX_CI_SEL,GUI_GRAY);
				// USER START (Optionally insert code for reacting on notification message)
					for(i=ID_EDIT_0; i<=ID_EDIT_8; i++) EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 0);	//disable focus
					EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, Id), 1);
					WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin),Id));
					sizeX[0] = WM_GetWindowSizeX(WM_GetClientWindow(ui_page.configUi));
					sizeY[0] = WM_GetWindowSizeY(WM_GetClientWindow(ui_page.configUi));
					sizeX[1] = WM_GetWindowSizeX(ui_page.windowSKB);
					sizeY[1] = WM_GetWindowSizeY(ui_page.windowSKB);
					/*if(sizeX[0] - WM_GetWindowOrgX(pMsg->hWinSrc) < sizeX[1]) posiX = sizeX[0] - sizeX[1];
					else posiX = WM_GetWindowOrgX(pMsg->hWinSrc);
					if(sizeY[0]-WM_GetWindowOrgY(pMsg->hWinSrc)-WM_GetWindowSizeY(pMsg->hWinSrc) < sizeY[1])
					posiY = WM_GetWindowOrgY(pMsg->hWinSrc) - sizeY[1];
					else posiY = WM_GetWindowOrgY(pMsg->hWinSrc) + WM_GetWindowSizeY(pMsg->hWinSrc);*/
					posiX=(800-sizeX[0])+1;
					posiY=300;
					ui_page.klindlistbox=CreateFramewinKindListBox();
					WM_MoveTo(ui_page.klindlistbox, posiX, posiY);
					//WM_ShowWindow(ui_page.windowSKB);
					//setWindowSKBtimerBoot(0);
					// USER END
					// USER END
					break;
					case WM_NOTIFICATION_RELEASED:
					// USER START (Optionally insert code for reacting on notification message)

					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					// USER START (Optionally insert additional code for further notification handling)
					// USER END   
					}
				break;
		case ID_BUTTON_0: // Notifications sent by 'Button'
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				case WM_NOTIFICATION_RELEASED:
					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.nominalSpeed = atof(editBuffer);
					//printf("_config_content.nominalSpeed %f m/s\r\n",(float)_config_content.nominalSpeed);
					//printf("_config_content.nominalSpeed1 %f m/s\r\n",1.0);
					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.diameter = atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.initSpeed= atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.SpeedV1= atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.SpeedV2= atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.accelerate1= atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.accelerate2= atof(editBuffer);

					hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
					EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
					_config_content.accelerate3= atof(editBuffer);

				

					_test_result_compare.scale =500/((_config_content.nominalSpeed)*10);
					//printf("_test_result_compare.scale=%d m/s\r\n",_test_result_compare.scale);
					_test_result_compare.diameter =(int)(_config_content.diameter/10);
					//printf("_test_result_compare.diameter=%d m/s\r\n",_test_result_compare.diameter);
					_test_result_compare.init_v= (int)(_config_content.initSpeed*100);
					//printf("_test_result_compare.init_v=%d m/s\r\n",_test_result_compare.init_v);
					_test_result_compare.accelerate_v1=((int)(_config_content.nominalSpeed*1150))-(int)(_config_content.nominalSpeed*1000)/2;
					//printf("_test_result_compare.accelerate_v1=%d m/s\r\n",_test_result_compare.accelerate_v1);
					_test_result_compare.accelerate_v2=((int)(_config_content.nominalSpeed*1150))-(int)(_config_content.nominalSpeed*1000)/5;
					//printf("_test_result_compare.accelerate_v2=%d m/s\r\n",_test_result_compare.accelerate_v2);

					hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
					if(_config_content.sort==-1){
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
						TEXT_SetText(hItem, "请选择");
						break;
					}
					_test_result_compare.result_v1=(int)(_config_content.nominalSpeed*115*10);//三位
					//printf("_test_result_compare.result_v1=%d m/s\r\n",_test_result_compare.result_v1);
					switch(_config_content.sort){
					
					case 0:
						if(_config_content.nominalSpeed>1.0){/*>115% <1.25v+0.25/v*/
							
							_test_result_compare.result_v2=(int)(_config_content.nominalSpeed*125*10+25000/(_config_content.nominalSpeed*100));//四舍五入
						//	printf("_test_result_compare.result_v2=%d m/s\r\n",_test_result_compare.result_v2);
						}else{//<=1.5
							_test_result_compare.result_v2=(int)1500;//三位
						//	printf("_test_result_compare.result_v2=%d m/s\r\n",_test_result_compare.result_v2);
						}
						break;
					case 1:
							if(_config_content.nominalSpeed>1.0){
								hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
								TEXT_SetText(hItem, "请输入正确的额定速度");
								return;
							}
							_test_result_compare.result_v2=(int)1000;//三位
						//	printf("_test_result_compare.result_v2=%d m/s\r\n",_test_result_compare.result_v2);
						break;
					case 2:
							if(_config_content.nominalSpeed>1.0){
								hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
								TEXT_SetText(hItem, "请输入正确的额定速度");
								return;
							}
							_test_result_compare.result_v2=(int)800;//三位
						//	printf("_test_result_compare.result_v2=%d m/s\r\n",_test_result_compare.result_v2);
						break;
					}
					
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
						TEXT_SetText(hItem, "");
					//GUI_EndDialog(ui_page.windowSKB, 0);
					DelWindowSKB();
					if(ui_page.klindlistbox!=0){
						GUI_EndDialog(ui_page.klindlistbox, 0);
						}
					GUI_EndDialog(pMsg->hWin, 0);
					ui_page.motorCtrlUI=CreateFramewinMotoCtrlUI();
					
					// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
				}
				break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				case WM_NOTIFICATION_RELEASED:
					//GUI_EndDialog(ui_page.windowSKB, 0);
					DelWindowSKB();
					GUI_EndDialog(pMsg->hWin, 0);
					ui_page.index=CreateFramewinIndex();

					// USER START (Optionally insert code for reacting on notification message)
					// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
				}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
			case ID_BUTTON_2: // Notifications sent by 'Button'
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				case WM_NOTIFICATION_RELEASED:
					//GUI_EndDialog(ui_page.windowSKB, 0);
					//createListBox();

					// USER START (Optionally insert code for reacting on notification message)
					// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
				}
			break;
		
		}
		default:
		WM_DefaultProc(pMsg);
		break;
		
 	 }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewinConfigUI(void);
WM_HWIN CreateFramewinConfigUI(void) {
  WM_HWIN hWin;
  button_Press.windowSKB=0;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

