/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include <string.h>
#include <stdlib.h>
#include "DIALOG.h"
#include "EmWinHZFont.h"
#include "FramewinDLG.h"
#include "backupIF.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_TEXT_3     (GUI_ID_USER + 0x04)
#define ID_TEXT_4     (GUI_ID_USER + 0x05)
#define ID_TEXT_5     (GUI_ID_USER + 0x06)

#define ID_EDIT_0     (GUI_ID_USER + 0x07)
#define ID_EDIT_1     (GUI_ID_USER + 0x08)
#define ID_EDIT_2     (GUI_ID_USER + 0x09)
#define ID_EDIT_3     (GUI_ID_USER + 0x0A)
#define ID_EDIT_4     (GUI_ID_USER + 0x0B)
#define ID_EDIT_5     (GUI_ID_USER + 0x0C)


#define ID_BUTTON_0     (GUI_ID_USER + 0x0D)
#define ID_BUTTON_1     (GUI_ID_USER + 0x0E)

#define ID_FOCUS_OPERATE  (GUI_ID_USER + 0xFF)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 85, 20, 200, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 85, 60, 200, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 85, 100, 200, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 85, 140, 200, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 85, 180, 200, 30, 0, 0x0, 0 },
   { TEXT_CreateIndirect, "Text", ID_TEXT_5, 85, 220, 200, 30, 0, 0x0, 0 },
   
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 318, 20, 360, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 318, 60, 360, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 318, 100, 360, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 318, 140, 360, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 318, 180, 360, 30, 0, 0x64, 0 },
   { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 318, 220, 360, 30, 0, 0x64, 0 },
   
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 156, 326, 102, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 382, 326, 102, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id,i;
	// USER START (Optionally insert additional variables)
	// USER END
	int posiX, posiY, sizeX[2], sizeY[2];
	static char editBuffer[36];
	static u32 temp111;
//	login_content  * _login_content_temp;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
	//是否第一次保存	
	
	BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), 0);
	BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), 0);
//	_login_content_temp = &_login_content;
	//
	// Initialization of 'Framewin'
	//
	hItem = pMsg->hWin;
	FRAMEWIN_SetTitleHeight(hItem, 36);
	FRAMEWIN_SetFont(hItem, &GUI_FontHZ16);
	FRAMEWIN_SetText(hItem, COMPANYNAME);
	FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);



	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "用户");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "电梯制造商");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "电梯型号");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "限速器制造商");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "限速器型号");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "限速器编号");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	// Initialization of 'Edit'
	//
	hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	//EDIT_SetMaxLen(hItem,4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[0] , 2017, 2017, 3000, 0, 0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.userNAME);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}

	//
	// Initialization of 'Edit'
	//
	hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	//EDIT_SetMaxLen(hItem,4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[1] , 1, 1, 12, 0,0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.liftManufactureNAME);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}
	//
	// Initialization of 'Edit'
	//
	hItem= WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	//EDIT_SetMaxLen(hItem,4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[2] , 1, 1, 31,0,0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.liftManufactureMODEL);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}
	//
	// Initialization of 'Edit'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
	//EDIT_SetMaxLen(hItem,4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[3] , 0, 0, 23, 0,0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.govenorManufactureNAME);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}
	//
	// Initialization of 'Edit'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
	//EDIT_SetMaxLen(editbox[4],4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[4] , 0, 0, 59, 0, 0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.govenorfactureMODEL);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}
	//
	// Initialization of 'Edit'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
	//EDIT_SetMaxLen(editbox[4],4);
	EDIT_SetFont(hItem,&GUI_FontHZ16);	
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//EDIT_SetDecMode(editbox[4] , 0, 0, 59, 0, 0);
	if(1==_backupUsr_boot.boot){
	sprintf(editBuffer, "%s",_backupUsr_info.backupUsr_information.govenorfactureNAME);
	EDIT_SetText(hItem, editBuffer);
	}
	else{
	EDIT_SetText(hItem, "");
	}

	
	// USER START (Optionally insert additional code for further widget initialization)
	// USER END

	//
	// Initialization of 'Button'
	//

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetFont(hItem,&GUI_FontHZ16);		
	BUTTON_SetText(hItem, "下一步");	
	//
	// Initialization of 'Button'
	//

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetFont(hItem,&GUI_FontHZ16);		
	BUTTON_SetText(hItem, "返回");	
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
	case ID_FOCUS_OPERATE:
		case WM_NOTIFICATION_USER:
	  		for( i=ID_EDIT_0; i<=ID_EDIT_5; i++) EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 1);	//enable focus
	  	break;
	break;
	case ID_EDIT_0:
		
	case ID_EDIT_1:
	case ID_EDIT_2:
	case ID_EDIT_3:
	case ID_EDIT_4:
	case ID_EDIT_5:
      switch(NCode) {
     
      case WM_NOTIFICATION_CLICKED:
	  	if(!button_Press.windowSKB){
			button_Press.windowSKB=1;
		  	WM_HideWindow(ui_page.windowSKB);
		  	for(i=ID_EDIT_0; i<=ID_EDIT_5; i++) EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 0);	//disable focus
		 	EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, Id), 1);
		 	WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin),Id));
			hItem = WM_GetDialogItem(pMsg->hWin, Id);
			EDIT_SetText(hItem, "\0");

	        // USER START (Optionally insert code for reacting on notification message)
			sizeX[0] = WM_GetWindowSizeX(WM_GetClientWindow(ui_page.logUi));
			sizeY[0] = WM_GetWindowSizeY(WM_GetClientWindow(ui_page.logUi));
			sizeX[1] = WM_GetWindowSizeX(ui_page.windowSKB);
			sizeY[1] = WM_GetWindowSizeY(ui_page.windowSKB);
			/*if(sizeX[0] - WM_GetWindowOrgX(pMsg->hWinSrc) < sizeX[1]) posiX = sizeX[0] - sizeX[1];
			else posiX = WM_GetWindowOrgX(pMsg->hWinSrc);
			if(sizeY[0]-WM_GetWindowOrgY(pMsg->hWinSrc)-WM_GetWindowSizeY(pMsg->hWinSrc) < sizeY[1])
			posiY = WM_GetWindowOrgY(pMsg->hWinSrc) - sizeY[1];
			else posiY = WM_GetWindowOrgY(pMsg->hWinSrc) + WM_GetWindowSizeY(pMsg->hWinSrc);*/
			posiX=(800-sizeX[1])/2;
			posiY=37;
			WM_MoveTo(ui_page.windowSKB, posiX, posiY);
			WM_ShowWindow(ui_page.windowSKB);
	  	}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END   
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  // USER START (Optionally insert code for reacting on notification message)
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	memcpy(_login_content.userNAME,editBuffer,sizeof(editBuffer));

	_login_content.userNAMElong=strlen(editBuffer);
	
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	memcpy(_login_content.liftManufactureNAME,editBuffer,sizeof(editBuffer));

	
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	//memcpy(_login_content.liftManufactureMODEL,editBuffer,strlen(editBuffer));
	memcpy(_login_content.liftManufactureMODEL,editBuffer,sizeof(editBuffer));

		
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	memcpy(_login_content.govenorManufactureNAME,editBuffer,sizeof(editBuffer));

		
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	_login_content.govenorfactureMODELlong=strlen(editBuffer);
	memcpy(_login_content.govenorfactureMODEL,editBuffer,sizeof(editBuffer));

		
	hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
	memcpy(_login_content.govenorfactureNAME,editBuffer,sizeof(editBuffer));

		

	//保存数据
	//if(!((_login_content.userNAME[0]==0x00)&&(_login_content.liftManufactureNAME[0]==0x00)&&(_login_content.govenorManufactureNAME[0]==0x00)))
	{
			
		if(!((strcmp(_login_content.userNAME, _backupUsr_info.backupUsr_information.userNAME) == 0)&&\
			(strcmp(_login_content.liftManufactureNAME,_backupUsr_info.backupUsr_information.liftManufactureNAME) == 0)&&\
			(strcmp(_login_content.govenorManufactureNAME,_backupUsr_info.backupUsr_information.govenorManufactureNAME) == 0)&&\
			(strcmp(_login_content.liftManufactureMODEL,_backupUsr_info.backupUsr_information.liftManufactureMODEL) == 0)&&\
			(strcmp(_login_content.govenorfactureMODEL,_backupUsr_info.backupUsr_information.govenorfactureMODEL) == 0)&&\
			(strcmp(_login_content.govenorfactureNAME,_backupUsr_info.backupUsr_information.govenorfactureNAME) == 0)))
		{
			if(0==_backupUsr_boot.boot){
				_backupUsr_info.startaddr=BACKUPUSRFOADDR;	
				
			}else{
				_backupUsr_info.startaddr=_backupUsr_info.endaddr;	
				
			}
			_backupUsr_info.endaddr=_backupUsr_info.startaddr+sizeof(backupUsr_info);

			if(_backupUsr_info.endaddr>(BACKUPUSRFOADDR+(2*4096)-1) )//如果超出扇区
			{
				W25QXX_Erase_Sector(BACKUPUSRFOADDR/4096);		//擦除这个扇区
				W25QXX_Erase_Sector((BACKUPUSRFOADDR/4096)+1);		//擦除这个扇区
				_backupUsr_info.startaddr=BACKUPUSRFOADDR;
				_backupUsr_info.endaddr=_backupUsr_info.startaddr+sizeof(backupUsr_info);
			}
			_backupUsr_info.backupUsr_information=_login_content;
			_backupUsr_info.flagok=0xa5;
			_backupUsr_boot.boot=1;//第一次保存但没有关机 _backupUsr_boot.boot没机会变为1
			
			W25QXX_Write_NoCheck((u8 *)(&_backupUsr_info),_backupUsr_info.startaddr,sizeof(backupUsr_info));
		}
	}
	
	//GUI_EndDialog(ui_page.windowSKB, 0);
	DelWindowSKB();
	GUI_EndDialog(pMsg->hWin, 0);
	ui_page.configUi=CreateFramewinConfigUI();
	ui_page.windowSKB=CreateWindowSKB();
	WM_AttachWindow(ui_page.windowSKB, ui_page.configUi);
	WM_HideWindow(ui_page.windowSKB);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  	//GUI_EndDialog(ui_page.windowSKB, 0);
	  	DelWindowSKB();
		GUI_EndDialog(pMsg->hWin, 0);
		ui_page.index=CreateFramewinIndex();
	  	
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewinLogUi(void);
WM_HWIN CreateFramewinLogUi(void) {
  WM_HWIN hWin;
button_Press.windowSKB=0;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
