/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "EmWinHZFont.h"
#include "FramewinDLG.h"
#include "rtc.h" 
#include <stdlib.h>
#include <string.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0      (GUI_ID_USER + 0x00)

#define ID_TEXT_0      (GUI_ID_USER + 0x01)
#define ID_TEXT_1      (GUI_ID_USER + 0x02)
#define ID_TEXT_2      (GUI_ID_USER + 0x03)
#define ID_TEXT_3      (GUI_ID_USER + 0x04)
#define ID_TEXT_4      (GUI_ID_USER + 0x05)
#define ID_TEXT_5      (GUI_ID_USER + 0x06)

#define ID_EDIT_0      (GUI_ID_USER + 0x07)
#define ID_EDIT_1      (GUI_ID_USER + 0x08)
#define ID_EDIT_2      (GUI_ID_USER + 0x09)
#define ID_EDIT_3      (GUI_ID_USER + 0x0A)
#define ID_EDIT_4      (GUI_ID_USER + 0x0B)
#define ID_EDIT_5      (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0      (GUI_ID_USER + 0x0D)
#define ID_BUTTON_1      (GUI_ID_USER + 0x0E)
#define ID_TEXT_6      (GUI_ID_USER + 0x0F)
#define ID_TEXT_7      (GUI_ID_USER + 0x10)
#define ID_TEXT_8      (GUI_ID_USER + 0x12)
#define ID_TEXT_9      (GUI_ID_USER + 0x13)
#define ID_TEXT_10      (GUI_ID_USER + 0x14)
#define ID_TEXT_11      (GUI_ID_USER + 0x15)
#define ID_TEXT_12      (GUI_ID_USER + 0x16)
#define ID_TEXT_13      (GUI_ID_USER + 0x17)
#define ID_TEXT_14      (GUI_ID_USER + 0x18)
#define ID_TEXT_15      (GUI_ID_USER + 0x19)
#define ID_TEXT_16      (GUI_ID_USER + 0x1A)
#define ID_TEXT_17      (GUI_ID_USER + 0x1B)
#define ID_TIMER      (GUI_ID_USER + 0x1c)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 249, 20, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 336, 20, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 336, 58, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 336, 95, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 336, 137, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 336, 170, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 336, 207, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 249, 56, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 249, 96, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 249, 137, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 249, 173, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 249, 206, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 245, 255, 102, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 427, 255, 102, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 160, 337, 114, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 160, 365, 54, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 207, 370, 18, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 219, 370, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 249, 370, 18, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 274, 370, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_12, 350, 370, 30, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_13, 380, 370, 19, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_14, 410, 370, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_15, 440, 370, 19, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_16, 470, 370, 30, 20, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "Text", ID_TEXT_17, 462, 370, 33, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  WM_HWIN editbox[6];
  int     NCode;
  int     Id,i;
  // USER START (Optionally insert additional variables)
  // USER END
  char editBuffer[5];
  int posiX, posiY, sizeX[2], sizeY[2];
  char timeString[4];
  _calendar_obj rtc_config;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), 0);
	BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), 0);
	//
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 36);
    FRAMEWIN_SetFont(hItem, &GUI_FontHZ16);
    FRAMEWIN_SetText(hItem, COMPANYNAME);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);


	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "年");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "月");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "日");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "时");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "分");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Text'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "秒");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "当前时间");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.w_year);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "-");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.w_month);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, "-");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.w_date);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.hour);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, ":");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.min);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	TEXT_SetText(hItem, ":");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
	TEXT_SetFont(hItem, &GUI_FontHZ16);
	sprintf(timeString, " %d" , calendar.sec);
	TEXT_SetText(hItem, (const char *)timeString);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

	//
	// Initialization of 'Button'
	//

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetFont(hItem,&GUI_FontHZ16);		
	BUTTON_SetText(hItem, "确认");	
	//
	// Initialization of 'Button'
	//

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetFont(hItem,&GUI_FontHZ16);		
	BUTTON_SetText(hItem, "返回");	

	//
    // Initialization of 'Edit'
    //
    editbox[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetMaxLen(editbox[0],4);
	EDIT_SetFont(editbox[0],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[0] , 2017, 2017, 3000, 0, 0);
	EDIT_SetText(editbox[0], "");
	
    //
    // Initialization of 'Edit'
    //
    editbox[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	EDIT_SetMaxLen(editbox[1],4);
    EDIT_SetFont(editbox[1],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[1] , 1, 1, 12, 0,0);
	EDIT_SetText(editbox[1], "");
    //
    // Initialization of 'Edit'
    //
    editbox[2] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	EDIT_SetMaxLen(editbox[2],4);
    EDIT_SetFont(editbox[2],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[2] , 1, 1, 31,0,0);
	EDIT_SetText(editbox[2], "");
    //
    // Initialization of 'Edit'
    //
    editbox[3] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
	EDIT_SetMaxLen(editbox[3],4);
    EDIT_SetFont(editbox[3],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[3] , 0, 0, 23, 0,0);
	EDIT_SetText(editbox[3], "");
    //
    // Initialization of 'Edit'
    //
    editbox[4] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
	EDIT_SetMaxLen(editbox[4],4);
    EDIT_SetFont(editbox[4],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[4] , 0, 0, 59, 0, 0);
	EDIT_SetText(editbox[4], "");
    //
    // Initialization of 'Edit'
    //
    editbox[5] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
	EDIT_SetMaxLen(editbox[5],4);
    EDIT_SetFont(editbox[5],&GUI_FontHZ16);	
	//EDIT_SetDecMode(editbox[5] , 0, 0, 59, 0, 0);
	EDIT_SetText(editbox[5], "");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;

  case WM_TIMER: 
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	sprintf(timeString, " %d" , calendar.w_year);
	TEXT_SetText(hItem, (const char *)timeString);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
	sprintf(timeString, " %d" , calendar.w_month);
	TEXT_SetText(hItem, (const char *)timeString);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
	sprintf(timeString, " %d" , calendar.w_date);
	TEXT_SetText(hItem, (const char *)timeString);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
	sprintf(timeString, " %d" , calendar.hour);
	TEXT_SetText(hItem, (const char *)timeString);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
	sprintf(timeString, " %d" , calendar.min);
	TEXT_SetText(hItem, (const char *)timeString);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
	sprintf(timeString, " %d" , calendar.sec);
	TEXT_SetText(hItem, (const char *)timeString);
	WM_RestartTimer(pMsg->Data.v, 1000);
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
		case ID_EDIT_0:
		case ID_EDIT_1:
		case ID_EDIT_2:
		case ID_EDIT_3:
		case ID_EDIT_4:
		case ID_EDIT_5:
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				//determine the keyboard position
					for(i=ID_EDIT_0; i<=ID_EDIT_5; i++) EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 0);	//disable focus
					EDIT_SetFocussable(WM_GetDialogItem(pMsg->hWin, Id), 1);
					WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin),Id));
					sizeX[0] = WM_GetWindowSizeX(WM_GetClientWindow(ui_page.configUi));
					sizeY[0] = WM_GetWindowSizeY(WM_GetClientWindow(ui_page.configUi));
					sizeX[1] = WM_GetWindowSizeX(ui_page.windowSKB);
					sizeY[1] = WM_GetWindowSizeY(ui_page.windowSKB);
					/*if(sizeX[0] - WM_GetWindowOrgX(pMsg->hWinSrc) < sizeX[1]) posiX = sizeX[0] - sizeX[1];
					else posiX = WM_GetWindowOrgX(pMsg->hWinSrc);
					if(sizeY[0]-WM_GetWindowOrgY(pMsg->hWinSrc)-WM_GetWindowSizeY(pMsg->hWinSrc) < sizeY[1])
					posiY = WM_GetWindowOrgY(pMsg->hWinSrc) - sizeY[1];
					else posiY = WM_GetWindowOrgY(pMsg->hWinSrc) + WM_GetWindowSizeY(pMsg->hWinSrc);*/
					posiX=(800-sizeX[1])/2;
					posiY=37;
					WM_MoveTo(ui_page.windowSKB, posiX, posiY);
					WM_ShowWindow(ui_page.windowSKB);
			break;
			case WM_NOTIFICATION_RELEASED:
				/*EDIT_GetText(WM_GetFocussedWindow(), &editBuffer[0], sizeof(editBuffer));
				switch(Id) {
				case ID_EDIT_0:
					
					rtc_config.w_year = (vu16)atoi(editBuffer);
					break;
				case ID_EDIT_1:
					rtc_config.w_month=  (vu8)atoi(editBuffer);
					break;
				case ID_EDIT_2:
					rtc_config.w_date=  (vu8)atoi(editBuffer);
					break;
				case ID_EDIT_3:
					rtc_config.hour=  (vu8)atoi(editBuffer);
					break;
				case ID_EDIT_4:
					rtc_config.min=  (vu8)atoi(editBuffer);
					break;
				case ID_EDIT_5:
					rtc_config.sec=  (vu8)atoi(editBuffer);
					break;
					}
			
				//WM_HIDEWindow(hPage[2]);*/
			break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  	{
			 hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		  	EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.w_year = (vu16)atoi(editBuffer);
			 hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
			EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.w_month=  (vu8)atoi(editBuffer);
			hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
			EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.w_date=  (vu8)atoi(editBuffer);
			hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
			EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.hour=  (vu8)atoi(editBuffer);
			hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
			EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.min=  (vu8)atoi(editBuffer);
			hItem  = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
			EDIT_GetText(hItem, &editBuffer[0], sizeof(editBuffer));
			rtc_config.sec=  (vu8)atoi(editBuffer);
			RTC_EnterConfigMode();/// 允许配置	
		  	RTC_Set(rtc_config.w_year,rtc_config.w_month,rtc_config.w_date,rtc_config.hour,rtc_config.min,rtc_config.sec);  //设置时间	
	        // USER START (Optionally insert code for reacting on notification message)
	        // USER END
	       	 RTC_ExitConfigMode(); //退出配置模式  
			BKP_WriteBackupRegister(BKP_DR1, 0X5050);
      	}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
  case ID_BUTTON_1: // Notifications sent by 'Button'
  	switch(NCode) {
  	case WM_NOTIFICATION_CLICKED:
    // USER START (Optionally insert code for reacting on notification message)
    // USER END
    	break;
  	case WM_NOTIFICATION_RELEASED:
		
		//GUI_EndDialog(ui_page.windowSKB, 0);
		DelWindowSKB();
		GUI_EndDialog(pMsg->hWin, 0);
		ui_page.index=CreateFramewinIndex();
		
    // USER START (Optionally insert code for reacting on notification message)
    // USER END
    	break;
  // USER START (Optionally insert additional code for further notification handling)
  // USER END
  }
  break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HTIMER hTimer;

WM_HWIN CreateFramewinTimeSet(void);
WM_HWIN CreateFramewinTimeSet(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hTimer = WM_CreateTimer(WM_GetClientWindow(hWin), ID_TIMER, 1000, 0); //1s
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
